# Auto-generated by bootstrap-ai-sync-auto.ps1 — do not edit manually.
# This file is regenerated each time the bootstrap runs.
param(
    [string]$RepoPath = (Join-Path $HOME '.ai-sync'),
    [string]$CliPath  = (Join-Path $HOME '.ai-sync-tools/ai-sync/dist/cli.js'),
    [string]$NodePath = 'node'
)

if (-not (Test-Path $RepoPath)) { exit 0 }
if (-not (Test-Path $CliPath))  { exit 0 }

$nodeCmd = Get-Command $NodePath -ErrorAction SilentlyContinue
if (-not $nodeCmd) { exit 0 }

Set-Location $RepoPath
& $nodeCmd.Source $CliPath push --no-update-check --repo-path $RepoPath 2>&1 | Out-Null
