<#
.SYNOPSIS
    Bootstrap the ai-sync auto-sync hook into the current user's PowerShell profile.
    Called by install.ps1 — you usually don't need to run this directly.

.PARAMETER SyncRepoPath
    Path to the local ai-sync config repo.

.PARAMETER CliPath
    Path to the ai-sync CLI entrypoint (dist/cli.js).
#>
param(
    [string]$SyncRepoPath = (Join-Path $HOME '.ai-sync'),
    [string]$CliPath      = (Join-Path $HOME '.ai-sync-tools/ai-sync/dist/cli.js')
)

$ErrorActionPreference = 'Stop'

$nodePath    = (Get-Command node -ErrorAction Stop).Source
$profilePath = $PROFILE.CurrentUserCurrentHost
$profileDir  = Split-Path $profilePath -Parent

if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}
if (-not (Test-Path $profilePath)) {
    New-Item -ItemType File -Path $profilePath -Force | Out-Null
}

# Build the auto-sync script dynamically
$autoScript = Join-Path (Split-Path $MyInvocation.MyCommand.Path -Parent) 'ai-sync-auto.ps1'

@"
# Auto-generated by bootstrap-ai-sync-auto.ps1 — do not edit manually.
param(
    [string]`$RepoPath = '$($SyncRepoPath -replace "'","''")',
    [string]`$CliPath  = '$($CliPath -replace "'","''")',
    [string]`$NodePath = '$($nodePath -replace "'","''")'
)

if (-not (Test-Path `$RepoPath)) { exit 0 }
if (-not (Test-Path `$CliPath))  { exit 0 }
if (-not (Test-Path `$NodePath)) { exit 0 }

Set-Location `$RepoPath
& `$NodePath `$CliPath push --no-update-check --repo-path `$RepoPath 2>&1 | Out-Null
"@ | Set-Content $autoScript -Force

# Install the profile hook (idempotent)
$hookMarker = '# >>> ai-sync auto-push >>>'
$hookEnd    = '# <<< ai-sync auto-push <<<'

$hookBlock = @"
$hookMarker
if (Test-Path '$($autoScript -replace "'","''")') {
    Start-Process powershell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File "$($autoScript -replace "'","''")"' -WindowStyle Hidden
}
$hookEnd
"@

$content = Get-Content $profilePath -Raw -ErrorAction SilentlyContinue
if ($content -and $content -match [regex]::Escape($hookMarker)) {
    $content = $content -replace "(?s)$([regex]::Escape($hookMarker)).*?$([regex]::Escape($hookEnd))\r?\n?", ''
    Set-Content -Path $profilePath -Value $content.TrimEnd()
}

Add-Content -Path $profilePath -Value "`n$hookBlock`n"

Write-Host "Bootstrap complete."
Write-Host "  Profile : $profilePath"
Write-Host "  Script  : $autoScript"
